#! /bin/bash

HADOOP=$(which hadoop)
MAVEN=$(which mvn)
DEFAULT_HDFS_HOST="hdfs://localhost:54310"

# help
if [ $# -eq 4 ]
then
HDFS_HOST=${DEFAULT_HDFS_HOST}
INPUT_PATH=$1
OUTPUT_PATH=$2
VECTOR_COUNT=$3
VECTOR_CARDINALITY=$4
elif [ $# -eq 5 ]
then
HDFS_HOST=$1
INPUT_PATH=$2
OUTPUT_PATH=$3
VECTOR_COUNT=$4
VECTOR_CARDINALITY=$5
else
	echo "Usage: $0 [{hdfs-host}] {input (on hdfs)} {output (on hdfs)} {vector-count} {vector-cardinality}"
	echo "calculates mean vector from the set of vectors contained in specified IntegerWritable-VectorWritable Sequence File."
	exit 1
fi

mvn exec:java -Dexec.mainClass="com.github.dongjinleekr.hadoop.vectormean.VectorMeanJob" -Dexec.args="\
-fs ${HDFS_HOST} \
-D log4j.logger.org.apache.hadoop=INFO \
-D mapred.map.child.java.opts=-Xmx4g \
-D mapred.reduce.child.java.opts=-Xmx4g \
-D local.cache.size=214748364800 \
-nr ${VECTOR_COUNT} \
-nc ${VECTOR_CARDINALITY} \
-i ${INPUT_PATH} \
-o ${OUTPUT_PATH} \
"
